### ISSUE TITLE
[MAIL] mu indexing does not work

### ISSUE THREAD

**Issue by ghost** [DiamondBond/emacs#24]
output of messages buffer

Loading /home/perrierjouet/.emacs.d/config.el (source)...
Loading /home/perrierjouet/.emacs.d/globals.el (source)...done
Function provided is already compiled [8 times]
Loading /home/perrierjouet/.emacs.d/config.el (source)...done
Loading /home/perrierjouet/.emacs.d/userconfig.el (source)...
Loading /home/perrierjouet/.emacs.d/modules/reddit.el (source)...done
Loading /home/perrierjouet/.emacs.d/modules/discord.el (source)...done
Loading /home/perrierjouet/.emacs.d/modules/mail.el (source)...done
Loading /home/perrierjouet/.emacs.d/userconfig.el (source)...done
Turning on magit-auto-revert-mode...done
[yas] Prepared just-in-time loading of snippets successfully.
For information about GNU Emacs and the GNU system, type C-h C-a.
Invalid face reference: quote [40 times]
Package cl is deprecated
[mu4e] Store is empty; try indexing (M-x mu4e-update-index).
Invalid face reference: quote [8 times]
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead. [4 times]
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘return’ is an obsolete alias (as of 27.1); use ‘cl-return’ instead.
.emacs.d/straight/build/calfw-org/calfw-org.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead. [2 times]
Created mpv link.
~/.emacs.d/straight/repos/mu/build/mu/mu index: exited abnormally with code 19.
cd ~/.emacs.d/straight/repos/mu; ./autogen.sh; ninja -C build: finished.
~/.emacs.d/straight/repos/mu/build/mu/mu init --maildir=~/mail/ --my-address=dagnachewa@gmail.com: exited abnormally with code 19.
~/.emacs.d/straight/repos/mu/build/mu/mu index: exited abnormally with code 19.

![image](https://user-images.githubusercontent.com/89839215/174900510-11ad8128-92fe-4aec-97cc-f49206d2943d.png)

**Comment by DiamondBond** [comment]
The three commands that exit abnormally with code 19 is normal if you already have mail setup locally, and mu4e works regardless, those commands are only needed for initial setup thats all.
Also thank you for figuring out the dependencies for mu4e on void (gmime-devel).

Regarding the failing mu indexing, do you have xapian installed?

edit

What happens if you press Shift + U in the mu4e-main view? (this calls the update email & db command), you may need to edit the local scripts that are written by mail.org to update with reference to your email details (not sure if this is necessary), i still need to figure out how to handle this dynamically and to source from globals.org, right now it might just be easier to define your own mu4e mail setup in your own mail.org or usermail.org or something - this is just a temporary workaround until i get around to building a robust portable solution for emacs mail. on that note, notmuch-emacs was what i was using before and it was working quite well and had an easy setup, i might implement this as an easier-to-setup mail module.

**Comment by ghost** [comment]
Yes I have xapian

**Comment by ghost** [comment]
manual indexing
/home/perrierjouet/.emacs.d/straight/repos/mu/build/mu  init
--maildir=~/mail/ ***@***.***
/home/perrierjouet/.emacs.d/straight/repos/mu/build/mu index
